### ISSUE TITLE
[kafka] Match messages received on  Produce requests with the described messages in the AsyncAPI doc

### ISSUE THREAD

**Issue by smoya** [asyncapi/event-gateway#10]
From [Kafka documentation](https://kafka.apache.org/protocol), this is all the info the `Produce Request` (Took version 8 as example): 

```
Produce Request (Version: 8) => transactional_id acks timeout_ms [topic_data] 
  transactional_id => NULLABLE_STRING
  acks => INT16
  timeout_ms => INT32
  topic_data => name [partition_data] 
    name => STRING
    partition_data => index records 
      index => INT32
      records => RECORDS
```

The app also knows the broker address the request was made to, It also has the mappings between Brokers and local ports.

At a glance, I see the app could find the channel by checking the **topic name** on the `Produce Request`, match it with channels within the AsyncAPI doc with an **Operation type** of `subscribe`.

However, this solution won't scale that much since we are assuming operations and messages are a 1:1 relationship, but this is subject to change in version 3 of the spec.
Would it make sense to introduce some identifier in the message so we can validate directly looking by that identifier?

**Comment by magicmatatjahu** [comment]
I think that this issue is related https://github.com/asyncapi/spec/issues/458 and `messageId` will be very handy in this case.

**Comment by smoya** [comment]
Yup, it is. Once `messageId` becomes a thing, it will be more easy to identify instead of guessing
