### ISSUE TITLE
Hosting of demo app - propose changes

### ISSUE THREAD

**Issue by derberg** [asyncapi/event-gateway#161]
Yo, do we need to host the demo app? Do we know if anyone is using it?\

I suggest we stop doing it as I wanted to propose we stop using Kubernetes in Digital Ocean:
- we stop deploying event gateway to kubernetes and if someone wants:
     - there can be instruction about using docker compose
     - we can just deploy super minimal demo directly using DO droplets
- we stop deploying `server-api` to K8s as well, and just use droplet to host it

It's all about money. K8s cluster costs $96 a month and we just ran out of all funds we had because of this high cost.

We did use K8s as we envisioned that we will have many different projects hosted there, so K8s was good option in case at some point of time we need to move somewhere else away from DO.

The future appeared to be different. Thus imho we should move away from K8s.

thoughts?

Of course I will ask DO to give us more budget. But this doesn't mean that we should continue what we do

**Comment by smoya** [comment]
+1 to, at least, move this into a Digital Ocean app instead of K8s.
Regarding if it make sense to keep it alive... atm I would tell you nobody uses it or even used it in the past. So I'm up for letting it go.

**Comment by derberg** [comment]
it surprises me that there are 51 stars, so looks like there is some interest.

> So I'm up for letting it go.

letting it go, you mean the whole project, to archive?

**Comment by derberg** [comment]
> letting it go, you mean the whole project, to archive?

right?

**Comment by smoya** [comment]
> it surprises me that there are 51 stars, so looks like there is some interest.
> 
> > So I'm up for letting it go.
> 
> letting it go, you mean the whole project, to archive?

No, I meant shutting down the demo app :)
Regarding the interest, yes it looks like, but more about adding features or supporting other protocols rather than Kafka (like https://github.com/asyncapi/event-gateway/issues/158), but no interest in collaborating so far :(

**Comment by derberg** [comment]
from my point of view, if there is no interest and no time for active maintenance from your side, we should just notify the TSC that this project is a candidate to be archived, and is there anyone who is things it is a bad move and is willing to jump in and help

**Comment by smoya** [comment]
For the record, the demo app was shut down time ago.
