### ISSUE TITLE
Find a name for the Gateway

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/event-gateway#2]
I'm opening this issue to hold discussion and ideas regarding the name of the "Event Gateway".

Ideas?

**Comment by MikeRalphson** [comment]
* [eventide](https://www.wordnik.com/words/eventide) though this might be more suited to an Event integrated development environment, and there is an [existing project](https://github.com/eventide-project)
* [Event One](http://doctorwhoworlduk.com/wp-content/uploads/2018/12/tardisdatac.jpg) - a reference to the Big Bang at the start of the universe, "one" indicating that the gateway is first in line for events

**Comment by derberg** [comment]
Eventgate! and the logo could be a dark room with a flashlight on

**Comment by derberg** [comment]
Everest - nice mountain for the logo and connection of words, event + rest, so you get the gateway and you can have a rest
<br>
![](https://media.giphy.com/media/3o85xr9ZKY1wbbJXDW/giphy.gif)

**Comment by smoya** [comment]
I really love the `eventide` @MikeRalphson suggested but also the `Everest` words combo @derberg  made here. 
Let's see if we can get more genius people into the game!

**Comment by emilianozublena** [comment]
- Eventacle: Word play between event + tentacle. Logo could be something related to octopuses, and i'm thinking on this extremely intelligent being that has a lot of hands(middlewares) that can do many wonderful things
- +1 to only calling it "Gate", like "AsyncAPI Gate", it's not something fancy, but for me it's very clear what this product does. And this could open up space to decouple the gate as much as it's possible (Gate would be the core product, and each middleware can have a diff name, and can be used or not, similar to how Golang plugins work)

**Comment by smoya** [comment]
@emilianozublena those names look cool as well!
I have some doubts regarding the word game on octopuses in particular because of KrakenD.
I think the "AsyncAPI Gate" is now my favorite :)

Btw, it would be awesome if you can share your usecase(s) through this new [Issue Template](https://github.com/asyncapi/event-gateway/issues/new?assignees=&labels=use+case&template=use_case.md&title=%5BUSECASE%5D+)

**Comment by emilianozublena** [comment]
Agreed, after re-reading my comment, im thinking "ohhh eventacle not so good idea" :P

i'll check the use cases asap. thx!

**Comment by smoya** [comment]
After some time with not so much activity on this issue, I'm gonna rise this again. 
At this moment, I vote for `Eventgate` as it is easy to remember and to understand.

What others think about it?

**Comment by gedw99** [comment]
Rendezvous - where Data meets !
